name: exam_dashboard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 0.20.2 
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.1
  dio: ^5.4.0     
  http: ^0.13.6
  pdf: ^3.10.4
  printing: ^5.12.0           # متوافق مع flutter_localizations من SDK
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0        # يمكنك تحديثها إلى ^6.0.0 لاحقاً إذا أردت

flutter:
  uses-material-design: true



